version: '3.8'

services:
  rdb:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: 'rdb'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'rootpassword'
    ports:
      - '3311:3306'
    volumes:
      - 'mysqldata:/var/lib/mysql'
volumes:
  mysqldata:
