datasource:
  rdb:
    writer:
      pool-name: rdb-writer
      username: root
      password: password
      driver-class-name: com.mysql.cj.jdbc.Driver
    reader:
      pool-name: rdb-reader
      username: root
      password: password
      driver-class-name: com.mysql.cj.jdbc.Driver

spring:
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
