datasource:
  rdb:
    writer:
      pool-name: rdb-writer
      jdbc-url: jdbc:mysql://127.0.0.1:3307/rdb
      username: user
      password: password
      driver-class-name: com.mysql.cj.jdbc.Driver
    reader:
      pool-name: rdb-reader
      jdbc-url: jdbc:mysql://127.0.0.1:3307/rdb
      username: user
      password: password
      driver-class-name: com.mysql.cj.jdbc.Driver

spring:
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    open-in-view: false
