name: Measure coverage

on:
  pull_request:
    types: [opened, synchronize, reopened]

  push:
    branches:
      - main

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: corretto
          java-version: 21
          cache: 'gradle'

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v3
      - name: Generate kover coverage report
        run: ./gradlew :application:koverXmlReport -x integrationTest

      - name: Add coverage report to PR
        id: kover
        uses: mi-kas/kover-report@v1
        with:
          path: |
            ${{ github.workspace }}/application/build/reports/kover/report.xml
          token: ${{ secrets.TOKEN }}
          title: Code Coverage
          update-comment: true
          min-coverage-overall: 80
          min-coverage-changed-files: 80
